### ISSUE TITLE
C++ std on macOS

### ISSUE THREAD

**Issue by henryiii** [conda-forge/cmake-feedstock#101]
The build currently hardcodes C++17:

Which is why it fails with the 10.9+ SDK on macOS, and requires 10.14.

I think we should use the default 10.9+ SDK, and allow it to select a lower C++ standard on macOS. The default C++ setting should be smart enough on CMake if we want to use that, or we should use 14 on macOS.

@isruf, thoughts?

**Comment by isuruf** [comment]
Sure. We use C++14 on macOS for other packages.

**Comment by henryiii** [comment]
See https://gitlab.kitware.com/cmake/cmake/issues/20054#note_663424

Is anything needed on top of #100? Is there a workaround somewhere in there that pulls in a newer libc++, etc?

**Comment by isuruf** [comment]
Yes, we can remove https://github.com/conda-forge/cmake-feedstock/blob/master/recipe/build.sh#L4-L17 and use C++14 standard.

**Comment by henryiii** [comment]
The recommendation from the CMake developers is to let CMake select the maximum version C++ version automatically, will make a PR for that.
