### ISSUE TITLE
cmake-gui does not work on windows

### ISSUE THREAD

**Issue by willyd** [conda-forge/cmake-feedstock#12]
When I try to start the cmake-gui installed with the cmake package I get the following error:
![error](https://cloud.githubusercontent.com/assets/628693/18112859/1e68daf8-6ef9-11e6-9431-2fa5cfcd92cd.png)
Installing package qt does not fix the problem.

Any ideas what could be done to fix this?

**Comment by willyd** [comment]
It seems this is not related to conda after all. Will raise the issue upstream.

**Comment by jakirkham** [comment]
Yeah we are just repackaging their binary for now on Windows. Though we would like to build from source. If you have time and interest, we would more than appreciate the help.

**Comment by blowekamp** [comment]
Can a recipe uses an older version of its own package? As I recall to bootstrap cmake you need cmake. 

https://cmake.org/install/
https://cmake.org/pipermail/cmake/2009-December/033819.html

**Comment by willyd** [comment]
I just submitted a PR to fix this issue. Turns out conda is really the cause of this problem.

**Comment by willyd** [comment]
@jakirkham Building from source would be optimal since the Qt dlls provided by this package will conflict with Qt dlls provided by other packages (PyQt. etc). I don't have time to look into this right now, but I may at some point.

**Comment by jakirkham** [comment]
Yeah, I'm not too stressed about getting the GUI part to work. Mostly people are using this to build other recipes where a GUI is irrelevant. In fact, that makes for a bulky dependency for CMake. Would prefer to not have the default `cmake` pull that in. Either it should be a different package or as an optional dependency ( https://github.com/conda/conda/issues/3299 ) once we have a way to do that.

**Comment by jschueller** [comment]
only cli is provided

**Comment by traversaro** [comment]
I am interested to provide cmake-gui as a different output of the package, there is any opinion on this before I start working on a PR?
