### ISSUE TITLE
error while loading shared libraries: libarchive.so.13: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 183amir** [conda-forge/cmake-feedstock#14]
```
/feedstock_root/build_artefacts/recipe_root_1474456931512/_t_env/bin/cmake: error while loading shared libraries: libarchive.so.13: cannot open shared object file: No such file or directory
```

full log: https://circleci.com/gh/conda-forge/bob.extension-feedstock/34?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by 183amir** [comment]
`cmake` is broken. I restarted one of my previously green builds and now it gives the same error:

Was green before: https://circleci.com/gh/conda-forge/bob.extension-feedstock/33

It is red now: https://circleci.com/gh/conda-forge/bob.extension-feedstock/36

**Comment by anjos** [comment]
This stopped working between versions 3.5.0-3 and 3.5.0-4.

https://github.com/conda-forge/cmake-feedstock/compare/089283d...b522876

Unfortunately, I can't know precisely to which tags builds 3 and 4 correspond, so these are my best guesses (green build, before switching to a higher number).

There are lots of changes here, but I think the most interesting is probably this:

https://github.com/conda-forge/cmake-feedstock/compare/089283d...b522876#diff-44a73bcc045c193c3bd45da87994b03bL5

That is effectively setting `LD_LIBRARY_PATH=${PREFIX}/lib` before running `make install`.

I wonder if that has an effect on the final cmake setup.

**Comment by 183amir** [comment]
@conda-forge/core could you look into this please? We can provide more info if you want.

**Comment by patricksnape** [comment]
Interesting. I've been using CMake for a lot of builds and haven't come across this. I wonder if this is a particular part of cmake being invoked?

**Comment by jakirkham** [comment]
Same. Also `libarchive` has basically been untouched version-wise since it was released on conda-forge back in June.

**Comment by anjos** [comment]
I think the issue with `libarchive` is circumstantial. It happens to be the first library loaded.

In our recipe, simply calling `cmake` makes it crash, so no special feature is being used.

See here, towards the end: https://circleci.com/gh/conda-forge/bob.extension-feedstock/41

**Comment by jakirkham** [comment]
Ok, so then I'm not sure why a build number bump would fix it. ( https://github.com/conda-forge/cmake-feedstock/pull/15 ) That fix would make sense if there was some versioning issue in the dependencies, but it sounds like that is not the case.

In any event, we just started to deploy packages for CMake 3.6.2. ( https://github.com/conda-forge/cmake-feedstock/pull/16 ) Hopefully that fixes some issues. If not, let us know.

**Comment by 183amir** [comment]
Updating to `3.6.2` did not help: https://circleci.com/gh/conda-forge/bob.extension-feedstock/42

As you can see, we just run `cmake` with no arguments as the first test command and it fails:
```
The following NEW packages will be INSTALLED:

    alabaster:       0.7.9-py27_0                  conda-forge (soft-link)
    babel:           2.3.4-py27_0                  conda-forge (soft-link)
    blas:            1.1-openblas                  conda-forge (soft-link)
    bob.extension:   2.3.1-py27_0                  local       (soft-link)
    boost:           1.61.0-py27_1                 conda-forge (soft-link)
    bzip2:           1.0.6-3                       defaults    (soft-link)
    ca-certificates: 2016.8.31-0                   conda-forge (soft-link)
    certifi:         2016.8.31-py27_0              conda-forge (soft-link)
    cmake:           3.6.2-0                       conda-forge (soft-link)
    coverage:        4.2-py27_0                    conda-forge (soft-link)
    curl:            7.49.1-1                      conda-forge (soft-link)
    docutils:        0.12-py27_0                   conda-forge (soft-link)
    expat:           2.1.0-2                       conda-forge (soft-link)
    freetype:        2.6.3-1                       conda-forge (soft-link)
    icu:             56.1-4                        conda-forge (soft-link)
    imagesize:       0.7.1-py27_0                  conda-forge (soft-link)
    jinja2:          2.8-py27_1                    conda-forge (soft-link)
    jsoncpp:         0.10.6-1                      conda-forge (soft-link)
    libarchive:      3.2.1-2                       conda-forge (soft-link)
    libblitz:        0.10-0                        conda-forge (soft-link)
    libgfortran:     3.0.0-1                       defaults    (soft-link)
    libiconv:        1.14-3                        conda-forge (soft-link)
    libpng:          1.6.24-0                      conda-forge (soft-link)
    markupsafe:      0.23-py27_0                   conda-forge (soft-link)
    ncurses:         5.9-9                         conda-forge (soft-link)
    nose:            1.3.7-py27_2                  conda-forge (soft-link)
    numpy:           1.11.1-py27_blas_openblas_201 conda-forge [blas_openblas] (soft-link)
    openblas:        0.2.18-5                      conda-forge (soft-link)
    openssl:         1.0.2h-2                      conda-forge (soft-link)
    pip:             8.1.2-py27_0                  conda-forge (soft-link)
    pkg-config:      0.28-1                        conda-forge (soft-link)
    pygments:        2.1.3-py27_1                  conda-forge (soft-link)
    python:          2.7.12-1                      conda-forge (soft-link)
    pytz:            2016.6.1-py27_0               conda-forge (soft-link)
    readline:        6.2-0                         conda-forge (soft-link)
    requests:        2.11.1-py27_0                 conda-forge (soft-link)
    setuptools:      26.1.1-py27_0                 conda-forge (soft-link)
    six:             1.10.0-py27_0                 conda-forge (soft-link)
    snowballstemmer: 1.2.1-py27_0                  conda-forge (soft-link)
    sphinx:          1.4.6-py27_0                  conda-forge (soft-link)
    sqlite:          3.13.0-1                      conda-forge (soft-link)
    tk:              8.5.19-0                      conda-forge (soft-link)
    wheel:           0.29.0-py27_0                 conda-forge (soft-link)
    xz:              5.2.2-0                       conda-forge (soft-link)
    zlib:            1.2.8-3                       conda-forge (soft-link)




+ cmake
cmake: error while loading shared libraries: libarchive.so.13: cannot open shared object file: No such file or directory
TESTS FAILED: bob.extension-2.3.1-py27_0
```
https://github.com/conda-forge/bob.extension-feedstock/pull/11/files#diff-e178b687b10a71a3348107ae3154e44cR50

**Comment by 183amir** [comment]
When I re-rendered the `bob.extension` feedstock the error went away!!!

Why? I have no idea: https://github.com/conda-forge/bob.extension-feedstock/pull/11/commits/b6a087f589dc6ce81e898f13fd5b1ef0be52cd0f

**Comment by jakirkham** [comment]
Was just about to say it seems like a red herring and re-rendering may fix it. My suspicion is there is a `conda-build` version `2.0.x` issue involved. Try playing around with it locally and see if you can narrow it down.

**Comment by jakirkham** [comment]
FYI this is probably a good reason as to why we can't just enable `conda-build` universally. Namely `cmake` will stop working.

Here is another [example]( https://circleci.com/gh/conda-forge/vigra-feedstock/37 ) of this failure.

cc @conda-forge/core

**Comment by jakirkham** [comment]
FYI this is probably a good reason as to why we can't just enable `conda-build` version `2.x` universally. Namely `cmake` will stop working until we have had a chance to rebuild `ncurses`.

Here is another [example]( https://circleci.com/gh/conda-forge/vigra-feedstock/37 ) of this failure.

cc @conda-forge/core

**Comment by jakirkham** [comment]
Saw a note about `ncurses` in a recent log. This is definitely a package that needs to be rebuilt for `conda-build` version `2.0.x`'s long prefixes to be used. Not sure if this is causing the problem or if it is a red herring. Will try to look closer. Please this issue ( https://github.com/conda-forge/conda-forge.github.io/issues/171 ) for the long prefix rebuild saga.

**Comment by Soumi7** [comment]
I am trying to host my app with heroku, I get this error :
```pytesseract.pytesseract.TesseractError: (127, 'tesseract: error while loading shared libraries: libarchive.so.13: cannot open shared object file: No such
```

I tried adding a buildpack, adding apt file with ```tesseract-ocr``` and ```tesseract-ocr-eng```. I added the config variable path as well. The error persists.

**Comment by HeyangQin** [comment]
`sudo apt install libarchive13` solves this issue for me

**Comment by jakirkham** [comment]
@HeyangQin if you are still seeing an error that looks like this one, it is very likely the error is new and totally different. Could you please raise a new issue using the bug template (and filling out all the requested information)? Thank you! 🙏

**Comment by h-vetinari** [comment]
It is indeed a totally different issue, but we don't need a new ticket for it, because it's not related to CMake, but rather the following: https://github.com/conda/conda-libmamba-solver/issues/283
