### ISSUE TITLE
ccmake broken

### ISSUE THREAD

**Issue by kyleabeauchamp** [conda-forge/cmake-feedstock#20]
When I try to run `ccmake ../path` I end up with the following error:

```
Error running cmake::LoadCache().  Aborting.
```

I wonder if #13 will fix this, not sure.

**Comment by shadowwalkersb** [comment]
On Mac, cmake versions 3.7 and 3.8.

```
$ ccmake .
dyld: Library not loaded: @rpath/libform.5.dylib
  Referenced from: /Users/shadow_walker/anaconda/envs/eman-env/bin/ccmake
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by shadowwalkersb** [comment]
My error is not the same as in OP, but still fits the title. Should this be a separate issue?
