### ISSUE TITLE
cmake -E tar command broken for certain zip files

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/cmake-feedstock#23]
Using the linux `conda-forge` cmake package (3.6.2_0), certain zip files fail to unzip using the `cmake -E tar xvf` command.  The command works using the cmake package from the `defaults` channel (3.6.3_0).  

I don't think this was a bugfix in the 3.6.3 release as the 3.3.1 release from the `defaults` channel also works as expected.

Example in the linux-anvil docker container.

```
# wget https://github.com/google/farmhash/archive/34c13ddfab0e35422f4c3979f360635a8c050260.zip
...
# conda install -c defaults cmake
...
# conda list cmake
# packages in environment at /opt/conda:
#
cmake                     3.6.3                         0    defaults
# cmake -E tar xvf 34c13ddfab0e35422f4c3979f360635a8c050260.zip 
x farmhash-34c13ddfab0e35422f4c3979f360635a8c050260/
...
# head farmhash-34c13ddfab0e35422f4c3979f360635a8c050260/configure
#! /bin/sh
# Guess values for system-dependent variables and create Makefiles.
# Generated by GNU Autoconf 2.69 for FarmHash 1.1.0.
#
# Report bugs to <farmhash-discuss@googlegroups.com>.
#
#
# Copyright (C) 1992-1996, 1998-2012 Free Software Foundation, Inc.
#
#
# rm -rf farmhash-34c13ddfab0e35422f4c3979f360635a8c050260/
# conda install -c conda-forge cmake
...
# conda list cmake
# packages in environment at /opt/conda:
#
cmake                     3.6.2                         0    conda-forge
# cmake -E tar xvf 34c13ddfab0e35422f4c3979f360635a8c050260.zip 
x farmhash-34c13ddfab0e35422f4c3979f360635a8c050260/
# head farmhash-34c13ddfab0e35422f4c3979f360635a8c050260/configure
#
```  

The contents of the `configure` file looks to be repeats of a single byte value rather than text when unpacked with the `conda-forge` cmake.

**Comment by jjhelmus** [comment]
I noticed that the `defaults` cmake package does not link against `libarchive` where as the `conda-forge` version is including this library.  I would assume is providing the unzip functionality.  The [anaconda-recipes build script](https://github.com/ContinuumIO/anaconda-recipes/blob/master/cmake/build.sh) explicitly include a `--no-system-libarchive` switch.

**Comment by jakirkham** [comment]
Could it be an issue with `libarchive` then?
