### ISSUE TITLE
ccmake broken on Mac

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/cmake-feedstock#35]
On Mac, cmake versions 3.7 and 3.8.

```
$ ccmake .
dyld: Library not loaded: @rpath/libform.5.dylib
  Referenced from: /Users/shadow_walker/anaconda/envs/eman-env/bin/ccmake
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by shadowwalkersb** [comment]
Why was this closed? I get complaints from users saying this is broken.

**Comment by jakirkham** [comment]
Probably an accident. I think I was meaning to close issue ( https://github.com/conda-forge/cmake-feedstock/issues/36 ) and must have gotten this one by mistake. Sorry about that.

**Comment by isuruf** [comment]
Are you using `ncurses` from `conda-forge` channel?

**Comment by shadowwalkersb** [comment]
I just found out that ncurses was coming from defaults. So, the problem here is the same as in #36 . So, this issue can be closed.
