### ISSUE TITLE
Broken Windows builds with CMake 3.9.0

### ISSUE THREAD

**Issue by wesm** [conda-forge/cmake-feedstock#38]
In diagnosing broken builds that started showing up in the last 24 hours I seem to have tracked it down to the CMake update to 3.9.0:

https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/build/1.0.2593/job/q484cyl1one8gn2l

here's the appveyor support case http://help.appveyor.com/discussions/problems/7188-odd-cmake-build-failures-unrelated-to-code-changes

**Comment by wesm** [comment]
Confirming that pinning cmake 3.8.0 fixed the builds

**Comment by scopatz** [comment]
Pull requests welcome!

**Comment by wesm** [comment]
I think @MaxRis is looking into this. It could be an upstream bug in CMake in which case we might want to pull the 3.9.0 release from conda-forge

**Comment by scopatz** [comment]
@wesm - OK.  I am relying on 3.9 for some of my stuff.  So pinning code that needs 3.8 seems like the better option.

**Comment by scopatz** [comment]
Though, admittedly, I am not relying on the windows build, so pulling that would be OK by me.

**Comment by jschueller** [comment]
seems they changed stuff related to the detection of msbuild:
https://cmake.org/cmake/help/v3.9/release/3.0.html
my feedstocks seem to run fine though

**Comment by MaxRis** [comment]
Have created [issue](https://gitlab.kitware.com/cmake/cmake/issues/17118) for this

**Comment by jschueller** [comment]
not yet uploaded
