### ISSUE TITLE
curl incompatibility issue

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/cmake-feedstock#53]
It turns out there is an ABI break (on OSX, at least) starting with curl `7.58`.

With `curl=7.55`, `libcurl.dylib` has `compatibility version 9.0.0`, but with `curl=7.58`, it has `compatibility version 10.0.0`.

<details>

Curl 7.55:

```
$ conda install -y curl=7.55
...

$ otool -L /miniforge/envs/curl/lib/libcurl.4.dylib
/miniforge/envs/curl/lib/libcurl.4.dylib:
	@rpath/libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
...
```

Curl 7.58:

...

```
$ conda install -y curl=7.58
...

$ otool -L /miniforge/envs/curl/lib/libcurl.4.dylib
/miniforge/envs/curl/lib/libcurl.4.dylib:
	@rpath/libcurl.4.dylib (compatibility version 10.0.0, current version 10.0.0)
...
```

</details>
<br>
When I try to run `cmake` in an environment with the older version of curl, I get this error:

```
dyld: Library not loaded: @rpath/libcurl.4.dylib
  Referenced from: /foo/foo/foo/bin/cmake
  Reason: Incompatible library version: cmake requires version 10.0.0 or later,
          but libcurl.4.dylib provides version 9.0.0
```

-----

Therefore, this recipe's constraints for `curl` appear to be too broad, at least on Mac:

```yaml
 - curl >=7.44.0,<8  # [unix]
```

I guess they ought to be either:

```yaml
 - curl >=7.44.0,<=7.55.0  # [unix]
```

or:

```yaml
 - curl >=7.58.0,<8  # [unix]
```

Note: I know `curl` is mentioned in the [pinnings settings][1], but I don't quite understand why that wasn't respected during the `cmake` build.  If it were, this error would not have popped up.

[1]: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

**Comment by scopatz** [comment]
Hi @stuarteberg - thanks for reporting!  I have not been seeing this issue on linux, and so I think the selectors should be only for osx, not unix.

**Comment by scopatz** [comment]
A pull request with a fix would be great!

**Comment by stuarteberg** [comment]
Any thoughts on how the conda-forge pinnings are supposed to play into this?  According to the pinnings, curl is supposed to be fixed at `7.44`.  I don't understand the pinning mechanism well enough to know if that matters.

**Comment by msarahan** [comment]
conda-forge-pinnings does not take effect when you are manually defining your pins, as you seem to be in this PR.  Might want to look at the chain in https://github.com/conda-forge/mpb-feedstock/pull/2#discussion_r184384413

**Comment by scopatz** [comment]
Well the pinnings state that curl needs to be *at least* v7.44, but less than v8 (which isn't out yet, I don't think).  So it is looser than being fixed at v7.44

**Comment by isuruf** [comment]
No the pinnings package say it should be `7.44.*` which should be fixed.

**Comment by scopatz** [comment]
I am seeing >=7.44.0,<8 in the recipe

**Comment by jakirkham** [comment]
That's taken from [the old pinnings]( https://github.com/conda-forge/conda-forge.github.io/blob/4c8b3b28ad45e6d46e268acf73de8c0da30de1bc/scripts/pin_the_slow_way.py#L70 ), which is true. Though @isuruf's point is the [new/current pinnings]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/3f3f3ae4933195e9c2dd6119b3a472e274028c40/recipe/conda_build_config.yaml#L212-L213 ) just specify `7.44.*`. In any event, this issue teaches us that both are wrong. So it doesn't matter much which one we look at. 😄

Right, @isuruf opened issue ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/47 ) to fix `curl` in the pinnings. Sounds like that is what we want, but feel free to comment over there if you have other thoughts.

**Comment by marcelotrevisani** [comment]
May we close this issue?

**Comment by stuarteberg** [comment]
Yes.  The latest version of the `cmake` package (`3.12.2`) lists the following constraints for `curl`, which resolve this issue:

`curl >=7.59.0,<8.0a0`

This was fixed via https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/52.
