### ISSUE TITLE
rebuild cmake 3.11.4 against ncurses 6.1?

### ISSUE THREAD

**Issue by lebedov** [conda-forge/cmake-feedstock#59]
Issue: cmake 3.11.4 currently depends on ncurses 5.9; this complicates its installation alongside packages that have been upgraded to depend on ncurses 6.1. Would it be possible to rebuild it against the latter?

**Comment by scopatz** [comment]
#57 will do this, but it is currently failing.  We could definitely use more eyes!

**Comment by lebedov** [comment]
Resolved.
