### ISSUE TITLE
libnsl not found

### ISSUE THREAD

**Issue by wolfv** [conda-forge/cmake-feedstock#69]
Issue: running cmake gives error libnsl not found

Running ldd shows that libnsl isn't linked/not found?

I am seeing libnsl though:

```
./x86_64-conda_cos6-linux-gnu/sysroot/lib/libnsl.so.1
./x86_64-conda_cos6-linux-gnu/sysroot/lib/libnsl-2.12.2.so
./x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/libnsl.so
./x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/libnsl.a
```

ldd output:

```
	linux-vdso.so.1 (0x00007ffe842aa000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f6b24e1c000)
	libexpat.so.1 => /home/wolfv/miniconda3/bin/./../lib/libexpat.so.1 (0x00007f6b24be7000)
	libz.so.1 => /home/wolfv/miniconda3/bin/./../lib/libz.so.1 (0x00007f6b249ca000)
	liblzma.so.5 => /home/wolfv/miniconda3/bin/./../lib/liblzma.so.5 (0x00007f6b24797000)
	libbz2.so.1.0 => /home/wolfv/miniconda3/bin/./../lib/libbz2.so.1.0 (0x00007f6b24587000)
	libcurl.so.4 => /home/wolfv/miniconda3/bin/./../lib/libcurl.so.4 (0x00007f6b2430b000)
	libuv.so.1 => /home/wolfv/miniconda3/bin/./../lib/libuv.so.1 (0x00007f6b240d7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6b23eb8000)
	libstdc++.so.6 => /home/wolfv/miniconda3/bin/./../lib/libstdc++.so.6 (0x00007f6b23b7e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6b237ea000)
	libgcc_s.so.1 => /home/wolfv/miniconda3/bin/./../lib/libgcc_s.so.1 (0x00007f6b235d8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6b23219000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6b25020000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f6b23011000)
	libssh2.so.1 => /home/wolfv/miniconda3/bin/./../lib/./libssh2.so.1 (0x00007f6b22dd9000)
	libssl.so.1.0.0 => /home/wolfv/miniconda3/bin/./../lib/./libssl.so.1.0.0 (0x00007f6b22b60000)
	libcrypto.so.1.0.0 => /home/wolfv/miniconda3/bin/./../lib/./libcrypto.so.1.0.0 (0x00007f6b2270f000)
	libgssapi_krb5.so.2 => /home/wolfv/miniconda3/bin/./../lib/./libgssapi_krb5.so.2 (0x00007f6b224c6000)
	libkrb5.so.3 => /home/wolfv/miniconda3/bin/./../lib/./libkrb5.so.3 (0x00007f6b221fa000)
	libk5crypto.so.3 => /home/wolfv/miniconda3/bin/./../lib/./libk5crypto.so.3 (0x00007f6b21fcb000)
	libcom_err.so.3 => /home/wolfv/miniconda3/bin/./../lib/./libcom_err.so.3 (0x00007f6b21dc8000)
	libnsl.so.1 => not found
	libkrb5support.so.0 => /home/wolfv/miniconda3/bin/./../lib/././libkrb5support.so.0 (0x00007f6b21bbd000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f6b219a6000)
```

I am going to try in an empty docker container to see if I can reproduce this issue.

**Comment by wolfv** [comment]
running this in a ubuntu docker container, it seems to link against the systems libnsl:

```
# ldd cmake
	linux-vdso.so.1 (0x00007ffd957f0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f090677b000)
	libexpat.so.1 => /root/miniconda3/bin/./../lib/libexpat.so.1 (0x00007f0906b6e000)
	libz.so.1 => /root/miniconda3/bin/./../lib/libz.so.1 (0x00007f0906564000)
	liblzma.so.5 => /root/miniconda3/bin/./../lib/liblzma.so.5 (0x00007f090633e000)
	libbz2.so.1.0 => /root/miniconda3/bin/./../lib/libbz2.so.1.0 (0x00007f090612c000)
	libcurl.so.4 => /root/miniconda3/bin/./../lib/libcurl.so.4 (0x00007f0905eb0000)
	libuv.so.1 => /root/miniconda3/bin/./../lib/libuv.so.1 (0x00007f0905c7c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0905a5d000)
	libstdc++.so.6 => /root/miniconda3/bin/./../lib/libstdc++.so.6 (0x00007f0906a2b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f09056bf000)
	libgcc_s.so.1 => /root/miniconda3/bin/./../lib/libgcc_s.so.1 (0x00007f0906a16000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f09052ce000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f090697f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f09050c6000)
	libssh2.so.1 => /root/miniconda3/bin/./../lib/./libssh2.so.1 (0x00007f0904e97000)
	libssl.so.1.0.0 => /root/miniconda3/bin/./../lib/./libssl.so.1.0.0 (0x00007f0904c1e000)
	libcrypto.so.1.0.0 => /root/miniconda3/bin/./../lib/./libcrypto.so.1.0.0 (0x00007f09047cd000)
	libgssapi_krb5.so.2 => /root/miniconda3/bin/./../lib/./libgssapi_krb5.so.2 (0x00007f0904584000)
	libkrb5.so.3 => /root/miniconda3/bin/./../lib/./libkrb5.so.3 (0x00007f09042b8000)
	libk5crypto.so.3 => /root/miniconda3/bin/./../lib/./libk5crypto.so.3 (0x00007f0904089000)
	libcom_err.so.3 => /root/miniconda3/bin/./../lib/./libcom_err.so.3 (0x00007f0903e86000)
	->>>>> libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f0903c6c000)
	libkrb5support.so.0 => /root/miniconda3/bin/./../lib/././libkrb5support.so.0 (0x00007f0903a61000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f0903846000)
# 
```

**Comment by marcelotrevisani** [comment]
humm.... that's a problem, I will try to investigate that

**Comment by wolfv** [comment]
Thanks!

**Comment by jakirkham** [comment]
> The libnsl package contains the public client interface for NIS(YP) and NIS+. It replaces the NIS library that used to be in glibc.

Taken from [Linux from Scratch]( http://www.linuxfromscratch.org/blfs/view/systemd/basicnet/libnsl.html ).

**Comment by jakirkham** [comment]
Could you please fill in the rest of the issue template, @wolfv? In particular would like to see the environment and more specifically the exact CMake package used. Just to confirm, this is Linux, right?

**Comment by scopatz** [comment]
`libnsl` comes from 1gcc_impl_linux-641, which I believe is one of the compiler packages that was copied from defaults into the conda-forge channel

**Comment by tadeu** [comment]
`libnsl` used to always be packaged together with `glibc`:

https://www.python.org/dev/peps/pep-0571/

On Debian-based systems it should be provided by the `libc6` package and on RPM-based systems it should be provided by the `glibc` package.

But it seems Fedora 28 broke this:

https://github.com/AppImage/AppImages/issues/336

**Comment by jakirkham** [comment]
Thanks for the details.

Does installing `libnsl` with `dnf` fix this for you?

**Comment by wolfv** [comment]
A version of libnsl is installed in the fedora system by default:

```
./usr/lib64/libnsl.so.2.0.0
./usr/lib64/libnsl.so.2
```

Installing libnsl indeed installs `libnsl.so.1` into `/usr/lib64/libnsl.so.1` and fixes the problem.

Is this the "correct" solution?

By the way, this is on a tangent, but I keep wondering if using something like `fakechroot` to build pacakges would help mitigate these link issues for binary packages by forcing the linker to not consider system packages at all.

**Comment by jakirkham** [comment]
FWIW it looks like this choice by Fedora was [very much intentional]( https://fedoraproject.org/wiki/Fedora_28_talking_points#NIS_switching_to_new_libnsl_to_support_IPv6 ). More details [here]( https://fedoraproject.org/wiki/Changes/NISIPv6 ).

cc @mingwandroid

**Comment by tadeu** [comment]
> A version of libnsl is installed in the fedora system by default

@wolfv, that one seems to be `libnsl2`, as a workaround try to also install `libnsl` with `sudo dnf install libnsl.so.1` or to make a link as described here:

https://github.com/oracle/node-oracledb/issues/892#issuecomment-387082011

**Comment by tadeu** [comment]
Here is a diff between the recipe in Anaconda and the one in conda-forge (`+`s are for the one in conda-forge):

```diff
 #!/bin/sh
-
-# Filter out -I${PREFIX}/include from CXXFLAGS as it causes issues with bad header
-# *and* macro name hygiene around libuv (queue.h / QUEUE etc, urgh).
-re="(.*[[:space:]])\-I${PREFIX}/include[^[:space:]]*(.*)"
-if [[ "${CXXFLAGS}" =~ $re ]]; then
-  export CXXFLAGS="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
-fi
-if [[ "${CFLAGS}" =~ $re ]]; then
-  export CFLAGS="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
-fi
+set -ex
 
 ./bootstrap \
+             --verbose \
              --prefix="${PREFIX}" \
              --system-libs \
+             --system-libuv \
              --no-qt-gui \
-             --no-system-libuv \
              --no-system-libarchive \
              --no-system-jsoncpp \
              --parallel=${CPU_COUNT} \
              -- \
+             -DCMAKE_BUILD_TYPE:STRING=Release \
              -DCMAKE_FIND_ROOT_PATH="${PREFIX}" \
              -DCMAKE_INSTALL_RPATH="${PREFIX}/lib" \
-             -DCMAKE_CXX=${CXX} \
-             -DCMAKE_CC=${CC} \
-             -DCMAKE_BUILD_TYPE:STRING=Release
-make install -j${CPU_COUNT} ${VERBOSE_CM}
+             -DCURSES_INCLUDE_PATH="${PREFIX}/include" \
+             -DBUILD_CursesDialog=ON
+make install -j${CPU_COUNT}
```

I guess that `--no-system-libuv` is the main difference.

**Comment by marcelotrevisani** [comment]
as @tadeu pointed, we can try to see if with the option ``no-system-libuv`` will be different

**Comment by jakirkham** [comment]
Hmm...does `libuv` have this issue as well? Seems like a plausible route of inquiry. If so, it would be better to fix this issue at the source of the problem.

**Comment by marcelotrevisani** [comment]
That's true, executing ``ldd -r`` in ``libuv`` we see
![image](https://user-images.githubusercontent.com/7882269/45965144-f7e46c80-c027-11e8-9e93-cdcd93c582a7.png)

**Comment by marcelotrevisani** [comment]
which is linking with the library in my system

**Comment by jakirkham** [comment]
Also seeing a similar thing on CentOS 6. Looking through CMake's other dependencies am not seeing any of them link to `libnsl` other than `libuv`. So that's likely the culprit.

**Comment by mingwandroid** [comment]
Isn't this just a system library you need to be installing?

**Comment by jakirkham** [comment]
To summarize the findings from earlier, basically all Linuxes included `libnsl` previously. Both us, wheel folks, and many other developers have implicitly assumed `libnsl` would come preincluded. Though Fedora 28 switched to `libnsl2` and dropped including `libnsl` by default. This breaks our previous assumption. Thus breaking `libuv` and anything that depends on it (`cmake` in our case).

Current recommendation is to install `libnsl` with `dnf` on Fedora 28 as you say. Not sure how long that path will remain viable given Fedora's move to `libnsl2` or whether other distros may follow. So we should probably discuss what our longer term plan is.

**Comment by marcelotrevisani** [comment]
We may package ``libnsl`` and it will avoid this problem.

But I think for now (as @tadeu said) we may disable ``libuv`` in ``cmake``.

**Comment by mingwandroid** [comment]
Removing that might remove server mode which is *highly* useful.

**Comment by mingwandroid** [comment]
Better off advising people to install this lib on their distro and Dockerfiles IMHO.

**Comment by marcelotrevisani** [comment]
Should we close this?

**Comment by PaoloRibeca** [comment]
No, you should not I think. You should package libnsl1 instead. I am working on a RHEL cluster that has libnsl2 installed, with no libnsl1, and several conda packages (blast for instance) are broken as a result, as they depend on libnsl1. I could fix that if I were root, but I am not
