### ISSUE TITLE
CMake needs OpenSSL

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cmake-feedstock#7]
We need to start build CMake with OpenSSL. This problem was encountered when @patricksnape was trying to build OpenCV 3.x. See his [comment]( https://github.com/conda-forge/opencv-feedstock/pull/16/files#r65872619 ) in the diff, which has been quoted below.

> @jakirkham @msarahan  This is a bit horrible. Not sure why this is required but looks like our cmake isn't correctly compiled with our SSL at the moment? This is illustrated by the `Not supported protocol` error in this [circleci build](https://circleci.com/gh/conda-forge/opencv-feedstock/35).

**Comment by jakirkham** [comment]
Just to clarify, @patricksnape this was just a UNIX issue or was this affecting Windows too?

**Comment by patricksnape** [comment]
I was only seeing it on Linux.
