### ISSUE TITLE
Build Windows from source?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cmake-feedstock#9]
Seems we are just copying binaries over for our Windows package. Would be really awesome if we built this from source. Hopefully, that would make it easier to extend the functionality in this package as well by adding needed dependencies.

**Comment by xantares** [comment]
From https://cmake.org/install/:
"In order to build CMake from a source tree on Windows, you must first install the latest binary version of CMake because it is used for building the source tree."
:)
